### ISSUE TITLE
可否提供类似于这些头像上的学校地标建筑的图片

### ISSUE THREAD

**Issue by Wusir2018** [CQUtug/CQULogo#1]
这是90年的时候，学校的微信头像上面的，可惜没有将这些地表建筑的logo开放出来，请问你这里有这些学校的地标建筑图片嘛。非常感谢！
![IMG_4377](https://user-images.githubusercontent.com/51500032/89095097-f858a600-d3fc-11ea-9432-359715c78250.PNG)

**Comment by nanmu42** [comment]
抱歉，没有这些内容，欢迎贡献。:)
